# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel_ui.ui'
#
# Created: Thu Jan 16 20:07:44 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 179)
        MainWindow.setMinimumSize(QtCore.QSize(542, 179))
        MainWindow.setMaximumSize(QtCore.QSize(542, 179))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.line_edit_outPath = QtGui.QLineEdit(self.centralwidget)
        self.line_edit_outPath.setObjectName("line_edit_outPath")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.line_edit_outPath)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.line_edit_filename = QtGui.QLineEdit(self.centralwidget)
        self.line_edit_filename.setObjectName("line_edit_filename")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.line_edit_filename)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.cmb_box_extension = QtGui.QComboBox(self.centralwidget)
        self.cmb_box_extension.setObjectName("cmb_box_extension")
        self.cmb_box_extension.addItem("")
        self.cmb_box_extension.addItem("")
        self.cmb_box_extension.addItem("")
        self.cmb_box_extension.addItem("")
        self.cmb_box_extension.addItem("")
        self.horizontalLayout_2.addWidget(self.cmb_box_extension)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.line_edit_prefix = QtGui.QLineEdit(self.centralwidget)
        self.line_edit_prefix.setObjectName("line_edit_prefix")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.line_edit_prefix)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.line_edit_suffix = QtGui.QLineEdit(self.centralwidget)
        self.line_edit_suffix.setObjectName("line_edit_suffix")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.line_edit_suffix)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancel = QtGui.QPushButton(self.centralwidget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_createWrite = QtGui.QPushButton(self.centralwidget)
        self.btn_createWrite.setObjectName("btn_createWrite")
        self.horizontalLayout.addWidget(self.btn_createWrite)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Output path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "     Filename:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "   Extension: ", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_box_extension.setItemText(0, QtGui.QApplication.translate("MainWindow", "same", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_box_extension.setItemText(1, QtGui.QApplication.translate("MainWindow", "exr", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_box_extension.setItemText(2, QtGui.QApplication.translate("MainWindow", "jpeg", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_box_extension.setItemText(3, QtGui.QApplication.translate("MainWindow", "png", None, QtGui.QApplication.UnicodeUTF8))
        self.cmb_box_extension.setItemText(4, QtGui.QApplication.translate("MainWindow", "tiff", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "         Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "         Suffix:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_createWrite.setText(QtGui.QApplication.translate("MainWindow", "Create Write", None, QtGui.QApplication.UnicodeUTF8))

